name: Update Now Playing Badge

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: repo
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Copy files to workspace
        run: |
          cp -r repo/* $GITHUB_WORKSPACE/
          rm -rf repo

      - name: Debug Directory Structure
        run: |
          echo "Current directory:"
          pwd
          echo "Files in current directory:"
          ls -la
          echo "Content of profile.md:"
          cat profile.md || echo "profile.md not found"
          echo "Content of songs.json:"
          cat songs.json || echo "songs.json not found"

      - name: Update Now Playing
        run: python .github/scripts/update_music.py
        
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add profile.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update Now Playing badge" && git push)
