name: Update Now Playing Badge

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-badge:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: RashiMrBRD
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          repository: RashiMrBRD/RashiMrBRD
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Debug Environment
        run: |
          echo "Environment variables:"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "PWD: $(pwd)"
          
          echo "\nDirectory structure:"
          tree $GITHUB_WORKSPACE || ls -R $GITHUB_WORKSPACE
          
          echo "\nChecking file permissions:"
          ls -la $GITHUB_WORKSPACE
          ls -la $GITHUB_WORKSPACE/.github/scripts/ || echo "Scripts directory not found"
          
          echo "\nChecking Python environment:"
          which python
          python --version

      - name: Update Now Playing
        run: |
          # Print current directory and files for debugging
          pwd
          ls -la
          
          # Run the script
          python .github/scripts/update_music.py
        
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add profile.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update Now Playing badge" && git push)
